version: "3"
services:
  plex:
    image: plexinc/pms-docker:public
    container_name: plex
    ports:
      - 32400:32400
    volumes:
      - ${DOCKERDIR}/appdata/plex:/config
      - ${DATADIR}/plex_library:/media
      - /dev/shm:/transcode
    environment:
      PLEX_UID: ${PUID}
      PLEX_GID: ${PGID}
      TZ: ${TZ}
    networks:
      - npm_proxy
    restart: unless-stopped
networks:
  web_proxy:
    external: true
